In [1]:
from __future__ import print_function
import torch

In [11]:
unInitTensor = torch.empty(5, 3) # 创建未初始化的 Tensors
print(unInitTensor)

longInitTensor = torch.zeros(5, 3, dtype=torch.long) # 0(long)填充
print(longInitTensor)

randInitTensor = torch.rand(5, 3) # 随机填充
print(randInitTensor)

x = torch.tensor([5.0, 3.])
print(x)

x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float) # 对象的size 相同, 覆盖dtype属性
print(x, x.size(), sep='\n')

tensor([[ 0.0000e+00, -3.6893e+19,  0.0000e+00],
        [-3.6893e+19,  7.0065e-45,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 1.6213e-01,  4.2934e-08,  1.6613e-07],
        [ 2.1765e-04,  2.1271e+23,  4.1298e-05]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[0.0508, 0.4538, 0.7925],
        [0.7348, 0.6197, 0.1112],
        [0.4175, 0.7986, 0.4972],
        [0.6169, 0.2477, 0.8940],
        [0.0135, 0.6834, 0.2397]])
tensor([5., 3.])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.8338, -1.0406,  2.5550],
        [-0.0144,  0.0238,  0.5866],
        [-0.8249,  0.5451, -0.5430],
        [ 0.1042,  0.4824,  1.4957],
        [ 1.1243,  0.5734,  0.9695]])
torch.Size([5, 3])


In [23]:
x = torch.ones(5, 3, dtype=torch.float)
y = torch.rand(5, 3, dtype=torch.float)
print(x + y)
print(torch.add(x, y))

result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

y.add_(x) # op_ 操作会用结果替代原变量
print(y)

print(result[:, 1])

tensor([[1.8695, 1.5975, 1.0956],
        [1.9073, 1.0913, 1.8277],
        [1.0709, 1.7738, 1.8941],
        [1.9831, 1.6594, 1.6619],
        [1.5096, 1.9608, 1.9512]])
tensor([[1.8695, 1.5975, 1.0956],
        [1.9073, 1.0913, 1.8277],
        [1.0709, 1.7738, 1.8941],
        [1.9831, 1.6594, 1.6619],
        [1.5096, 1.9608, 1.9512]])
tensor([[1.8695, 1.5975, 1.0956],
        [1.9073, 1.0913, 1.8277],
        [1.0709, 1.7738, 1.8941],
        [1.9831, 1.6594, 1.6619],
        [1.5096, 1.9608, 1.9512]])
tensor([[1.8695, 1.5975, 1.0956],
        [1.9073, 1.0913, 1.8277],
        [1.0709, 1.7738, 1.8941],
        [1.9831, 1.6594, 1.6619],
        [1.5096, 1.9608, 1.9512]])
tensor([1.5975, 1.0913, 1.7738, 1.6594, 1.9608])


In [26]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
x.size(), y.size(), z.size()

(torch.Size([4, 4]), torch.Size([16]), torch.Size([2, 8]))

In [34]:
x = torch.randn(1)
x, x.item()

(tensor([-1.7352]), -1.735228180885315)

In [35]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [36]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [37]:
a.add_(1), b # ndarray b 也会更改

(tensor([2., 2., 2., 2., 2.]), array([2., 2., 2., 2., 2.], dtype=float32))

In [38]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a) # Tensor b也会更改
np.add(a, 1, out=a)
a, b

(array([2., 2., 2., 2., 2.]),
 tensor([2., 2., 2., 2., 2.], dtype=torch.float64))