In [1]:
import torch
import numpy as np

In [2]:
x = torch.ones(2, 2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [3]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [4]:
y.grad_fn

In [5]:
z = y * y * 3
print(z.requires_grad)
out = z.mean()
z, out

True


(tensor([[27., 27.],
         [27., 27.]], grad_fn=<MulBackward0>),
 tensor(27., grad_fn=<MeanBackward1>))

In [6]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad) # 默认 flag=False
a.requires_grad_(True)
print(a.requires_grad) # 手动开启梯度检测
b = (a * a).sum()
print(b.requires_grad, b.grad_fn)

False
True
True <SumBackward0 object at 0x124d89278>


In [7]:
out.backward() # 相当于 out.background(torch.tensor(1))

$\displaystyle  out = \frac{3(x+2)^2}{4}$   $\displaystyle  \frac{dout}{dx} = \frac{6(x+1)}{4}$

In [8]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [9]:
x = torch.randn(3, requires_grad=True)
y = x * 2
cnt = 0
while y.data.norm() < 1000:
    y = y * 2
    cnt += 1
y, cnt

(tensor([-351.1093, -497.1751,  796.9567], grad_fn=<MulBackward0>), 8)

In [10]:
gradients = torch.tensor([0.1, 1, 0.001], dtype=torch.float)
y.backward(gradients, retain_graph=True)
x, x.grad

(tensor([-0.6858, -0.9710,  1.5566], requires_grad=True),
 tensor([ 51.2000, 512.0000,   0.5120]))

In [11]:
x.requires_grad, (x ** 2).requires_grad, x.requires_grad_(requires_grad=False), x.requires_grad

(True, True, tensor([-0.6858, -0.9710,  1.5566]), False)

In [12]:
with torch.no_grad():
    print((x**2).requires_grad)

False
